#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
chezmoi_bin_dir="${CHEZMOI_BIN_DIR:-$HOME/.local/bin}"
shell_env="$HOME/.config/dotfiles/shell-env.sh"
tool_prefix="${DOTFILES_TOOL_PREFIX:-$HOME/.local/share/dotfiles/toolchain}"
tool_bin="$tool_prefix/bin"

export PATH="$tool_bin:$chezmoi_bin_dir:$PATH"

has() {
  command -v "$1" >/dev/null 2>&1
}

load_secrets_env() {
  local secrets_env
  secrets_env="${DOTFILES_SECRETS_ENV:-$HOME/.config/dotfiles/secrets.env}"

  if [[ ! -r "$secrets_env" ]]; then
    printf 'No local secrets env found at %s\n' "$secrets_env"
    printf 'If templates need tokens, run ./scripts/secrets-install.sh first or export the variables manually.\n'
    return
  fi

  set -a
  # shellcheck disable=SC1090
  . "$secrets_env"
  set +a
  printf 'Loaded local secrets env from %s\n' "$secrets_env"
}

toml_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

detect_platform() {
  local kernel distro
  kernel="$(uname -s 2>/dev/null || printf unknown)"

  if [[ "$kernel" == "Darwin" ]]; then
    printf 'macOS'
    return
  fi

  if [[ -r /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    distro="${PRETTY_NAME:-${NAME:-${ID:-Linux}}}"
    printf '%s' "$distro"
    return
  fi

  printf '%s' "$kernel"
}

install_chezmoi_official() {
  local platform
  platform="$(detect_platform)"

  mkdir -p -- "$chezmoi_bin_dir"

  if [[ -x "$chezmoi_bin_dir/chezmoi" ]]; then
    printf 'chezmoi already installed at %s\n' "$chezmoi_bin_dir/chezmoi"
    return
  fi

  printf 'Installing chezmoi with the official installer on %s...\n' "$platform"
  printf 'Install directory: %s\n' "$chezmoi_bin_dir"

  if has curl; then
    sh -c "$(curl -fsLS https://get.chezmoi.io)" -- -b "$chezmoi_bin_dir"
  elif has wget; then
    sh -c "$(wget -qO- https://get.chezmoi.io)" -- -b "$chezmoi_bin_dir"
  else
    printf 'Neither curl nor wget is installed, so the official chezmoi installer cannot be downloaded.\n' >&2
    printf 'Install curl or wget first, then rerun this script.\n' >&2
    exit 1
  fi
}

write_shell_env() {
  local rc_file
  mkdir -p -- "$(dirname -- "$shell_env")" "$chezmoi_bin_dir"

  cat > "$shell_env" <<EOF
# Generated by dotfiles. Safe to source from zsh, bash, and scripts.
export PATH="$tool_bin:$chezmoi_bin_dir:\$PATH"

export DOTFILES_TOOL_PREFIX="$tool_prefix"
export MAMBA_ROOT_PREFIX="\${MAMBA_ROOT_PREFIX:-$HOME/.local/share/micromamba}"
export NVM_DIR="\${NVM_DIR:-$HOME/.nvm}"
[ -s "\$NVM_DIR/nvm.sh" ] && . "\$NVM_DIR/nvm.sh"
if [ -n "\${BASH_VERSION:-}" ] && [ -s "\$NVM_DIR/bash_completion" ]; then
  . "\$NVM_DIR/bash_completion"
fi
EOF

  # shellcheck disable=SC1090
  . "$shell_env"

  for rc_file in "$HOME/.zshrc" "$HOME/.zprofile" "$HOME/.bashrc" "$HOME/.profile"; do
    [[ -e "$rc_file" ]] || touch "$rc_file"
    if ! grep -Fq '$HOME/.config/dotfiles/shell-env.sh' "$rc_file" 2>/dev/null; then
      {
        printf '\n'
        printf '# Dotfiles tool environment\n'
        printf '[ ! -f "$HOME/.config/dotfiles/shell-env.sh" ] || . "$HOME/.config/dotfiles/shell-env.sh"\n'
      } >> "$rc_file"
    fi
  done

  for rc_file in "$HOME/.bash_profile" "$HOME/.bash_login"; do
    [[ -e "$rc_file" ]] || continue
    if ! grep -Fq '$HOME/.config/dotfiles/shell-env.sh' "$rc_file" 2>/dev/null; then
      {
        printf '\n'
        printf '# Dotfiles tool environment\n'
        printf '[ ! -f "$HOME/.config/dotfiles/shell-env.sh" ] || . "$HOME/.config/dotfiles/shell-env.sh"\n'
      } >> "$rc_file"
    fi
  done
}

configure_chezmoi_source() {
  local config_home config_file escaped_source

  config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
  config_file="${CHEZMOI_CONFIG_FILE:-$config_home/chezmoi/chezmoi.toml}"
  escaped_source="$(toml_escape "$repo_root")"

  if [[ ! -e "$config_file" ]]; then
    mkdir -p -- "$(dirname -- "$config_file")"
    printf 'sourceDir = "%s"\n' "$escaped_source" > "$config_file"
    printf 'Configured chezmoi sourceDir in %s\n' "$config_file"
    return
  fi

  if grep -Eq '^[[:space:]]*sourceDir[[:space:]]*=' "$config_file"; then
    printf 'Using existing chezmoi config: %s\n' "$config_file"
    return
  fi

  {
    printf '\n'
    printf 'sourceDir = "%s"\n' "$escaped_source"
  } >> "$config_file"
  printf 'Added chezmoi sourceDir to %s\n' "$config_file"
}

write_shell_env

if ! has chezmoi; then
  install_chezmoi_official
fi

configure_chezmoi_source
load_secrets_env

chezmoi --source "$repo_root" diff

printf '\nReview the diff above. Apply with:\n  chezmoi --source %q apply\n' "$repo_root"
