#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
src_home="${HOME:?HOME is not set}"

need() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'Missing required command: %s\n' "$1" >&2
    exit 1
  }
}

copy_file() {
  local src="$1"
  local dst="$2"
  [[ -f "$src" ]] || return 0
  mkdir -p -- "$(dirname -- "$dst")"
  cp -p -- "$src" "$dst"
}

copy_tree() {
  local src="$1"
  local dst="$2"
  shift 2
  [[ -d "$src" ]] || return 0
  mkdir -p -- "$dst"
  rsync -a --delete --delete-excluded "$@" "$src"/ "$dst"/
}

remove_tree_symlinks() {
  local dst="$1"
  [[ -d "$dst" ]] || return 0
  find "$dst" -type l -delete
}

sanitize_zprofile() {
  local src="$src_home/.zprofile"
  local dst="$repo_root/dot_zprofile"
  [[ -f "$src" ]] || return 0
  copy_file "$src" "$dst"

  perl -0pi -e '
    s{^eval "\$\(/opt/homebrew/bin/brew shellenv\)"$}{q{if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi}}egm;
  ' "$dst"

  if ! grep -Fq '$HOME/.config/dotfiles/shell-env.sh' "$dst"; then
    {
      printf '\n'
      printf '[ ! -f "$HOME/.config/dotfiles/shell-env.sh" ] || . "$HOME/.config/dotfiles/shell-env.sh"\n'
    } >> "$dst"
  fi
}

sanitize_zshrc() {
  local src="$src_home/.zshrc"
  local dst="$repo_root/private_dot_zshrc.tmpl"
  [[ -f "$src" ]] || return 0
  perl -0pe '
    s/# Mistral OCR.*?export JINA_API_KEY="[^\n]*"/# Private workflow tokens. This file is generated by scripts\/secrets-install.sh.\n[ ! -f "$HOME\/.config\/dotfiles\/secrets.env" ] || source "$HOME\/.config\/dotfiles\/secrets.env"/s;
  ' "$src" > "$dst"
  harden_zshrc_template "$dst"
  ensure_zsh_helpers "$dst"
}

harden_zshrc_template() {
  local dst="$1"

  perl -0pi -e '
    s{^eval "\$\(zoxide init zsh\)"$}{q{if (( ${+commands[zoxide]} )); then
  eval "$(zoxide init zsh)"
fi}}egm;
    s{^eval "\$\(starship init zsh\)"$}{q{if (( ${+commands[starship]} )); then
  eval "$(starship init zsh)"
fi}}egm;
    s{^\[ -s "\$NVM_DIR/bash_completion" \] && \\\.? "\$NVM_DIR/bash_completion"$}{q{if [[ -n "${BASH_VERSION:-}" && -s "$NVM_DIR/bash_completion" ]]; then
  . "$NVM_DIR/bash_completion"
fi}}egm;
    s{^\[ -s "\$NVM_DIR/bash_completion" \] && \. "\$NVM_DIR/bash_completion"$}{q{if [[ -n "${BASH_VERSION:-}" && -s "$NVM_DIR/bash_completion" ]]; then
  . "$NVM_DIR/bash_completion"
fi}}egm;
    s{^\Q. "$HOME/.local/bin/env"\E$}{q{[ ! -f "$HOME/.config/dotfiles/shell-env.sh" ] || . "$HOME/.config/dotfiles/shell-env.sh"
[ ! -f "$HOME/.local/bin/env" ] || . "$HOME/.local/bin/env"}}egm;
    s{^proxy_on$}{q{if [[ "${DOTFILES_AUTO_PROXY:-0}" == "1" ]]; then
  proxy_on
fi}}egm;
    s{^export PATH="/Applications/Xpra\.app/Contents/MacOS:\$PATH"$}{q{if [[ "$OSTYPE" == darwin* ]]; then
  export PATH="/Applications/Xpra.app/Contents/MacOS:$PATH"
fi}}egm;
    s{curl -fsSL --create-dirs -o \$\{ZIM_HOME\}/zimfw\.zsh\n        https://github\.com/zimfw/zimfw/releases/latest/download/zimfw\.zsh$}{q{curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh || true}}egm;
    s{else\n    mkdir -p \$\{ZIM_HOME\} && wget -nv -O \$\{ZIM_HOME\}/zimfw\.zsh\n        https://github\.com/zimfw/zimfw/releases/latest/download/zimfw\.zsh$}{q{elif (( ${+commands[wget]} )); then
    mkdir -p ${ZIM_HOME} && wget -nv -O ${ZIM_HOME}/zimfw.zsh
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh || true}}egm;
    s{if \[\[ ! \$\{ZIM_HOME\}/init\.zsh -nt \$\{ZIM_CONFIG_FILE:-\$\{ZDOTDIR:-\$\{HOME\}\}/\.zimrc\} \]\]; then\n  source \$\{ZIM_HOME\}/zimfw\.zsh init\nfi}{q{if [[ -r ${ZIM_HOME}/zimfw.zsh && ! ${ZIM_HOME}/init.zsh -nt ${ZIM_CONFIG_FILE:-${ZDOTDIR:-${HOME}}/.zimrc} ]]; then
  source ${ZIM_HOME}/zimfw.zsh init || true
fi}}eg;
    s{^source \$\{ZIM_HOME\}/init\.zsh$}{q{[[ ! -r ${ZIM_HOME}/init.zsh ]] || source ${ZIM_HOME}/init.zsh}}egm;
  ' "$dst"

  if ! grep -Fq '_dotfiles_prepend_fpath_dir()' "$dst"; then
    perl -0pi -e 's{(\n# --------------------\n# Module configuration)}{q{

#
# User-local toolchain
#

[ ! -f "$HOME/.config/dotfiles/shell-env.sh" ] || . "$HOME/.config/dotfiles/shell-env.sh"

_dotfiles_prepend_fpath_dir() {
  local dir="$1"
  [[ -d "$dir" ]] || return
  fpath=("$dir" ${fpath:#"$dir"})
}

for _dotfiles_zsh_prefix in \
  "${DOTFILES_TOOL_PREFIX:-}" \
  "${CONDA_PREFIX:-}" \
  "$HOME/.local/share/dotfiles/toolchain"; do
  [[ -n "$_dotfiles_zsh_prefix" ]] || continue
  _dotfiles_prepend_fpath_dir "$_dotfiles_zsh_prefix/share/zsh/site-functions"
  _dotfiles_prepend_fpath_dir "$_dotfiles_zsh_prefix/share/zsh/functions"
  _dotfiles_prepend_fpath_dir "$_dotfiles_zsh_prefix/share/zsh/$ZSH_VERSION/functions"
  for _dotfiles_zsh_dir in \
    "$_dotfiles_zsh_prefix"/share/zsh/functions/*(N-/) \
    "$_dotfiles_zsh_prefix"/share/zsh/$ZSH_VERSION/functions/*(N-/) \
    "$_dotfiles_zsh_prefix"/share/zsh/*/functions(N-/) \
    "$_dotfiles_zsh_prefix"/share/zsh/*/functions/*(N-/); do
    _dotfiles_prepend_fpath_dir "$_dotfiles_zsh_dir"
  done
done
unset _dotfiles_zsh_prefix _dotfiles_zsh_dir
} . $1}e' "$dst"
  fi

  if ! grep -Fq '_dotfiles_repair_zsh_compinit_permissions()' "$dst"; then
    perl -0pi -e 's{(ZIM_HOME=\$\{ZDOTDIR:-\$\{HOME\}\}/\.zim\n)}{$1 . q{
_dotfiles_repair_zsh_compinit_permissions() {
  local dir
  for dir in "$HOME" "$ZIM_HOME" "${DOTFILES_TOOL_PREFIX:-}/share/zsh"; do
    [[ -d "$dir" ]] || continue
    if [[ "$dir" == "$HOME" ]]; then
      command chmod go-w "$dir" 2>/dev/null || true
    else
      command chmod -R go-w "$dir" 2>/dev/null || true
    fi
  done
}
}}e' "$dst"
  fi

  if grep -Fq '_dotfiles_repair_zsh_compinit_permissions()' "$dst" &&
     ! grep -Fq '_dotfiles_repair_zsh_compinit_permissions
# Initialize modules.' "$dst"; then
    perl -0pi -e 's{(\n# Initialize modules\.)}{\n_dotfiles_repair_zsh_compinit_permissions$1}' "$dst"
  fi

  if ! grep -Fq '$HOME/.config/dotfiles/shell-env.sh' "$dst"; then
    {
      printf '\n'
      printf '[ ! -f "$HOME/.config/dotfiles/shell-env.sh" ] || . "$HOME/.config/dotfiles/shell-env.sh"\n'
    } >> "$dst"
  fi
}

ensure_zsh_helpers() {
  local dst="$1"

  if grep -q '^dotup() {' "$dst"; then
    return
  fi

  cat >> "$dst" <<'ZSH_HELPERS_EOF'

_dotfiles_repo() {
  local repo
  for repo in \
    "${DOTFILES_REPO:-}" \
    "$HOME/dotfiles" \
    "$HOME/.local/share/chezmoi" \
    "/Users/macbook/Documents/Codex/2026-05-09/create-dotfile-chezmoi-codex-claude-tmux/dotfiles"; do
    if [ -n "$repo" ] && [ -d "$repo/.git" ] && [ -x "$repo/scripts/bootstrap.sh" ]; then
      printf '%s\n' "$repo"
      return 0
    fi
  done
  printf 'dotfiles repo not found. Set DOTFILES_REPO=/path/to/dotfiles.\n' >&2
  return 1
}

_dotfiles_git_preflight() {
  if ! git config user.name >/dev/null 2>&1 || ! git config user.email >/dev/null 2>&1; then
    cat >&2 <<'EOF'
Git identity is not configured yet.

Run once on this machine:
  git config --global user.name "BoChao1Zhang"
  git config --global user.email "3210191548@qq.com"

EOF
    return 1
  fi

  local remote_url
  remote_url="$(git remote get-url origin 2>/dev/null || true)"
  case "$remote_url" in
    https://github.com/*)
      cat >&2 <<'EOF'
GitHub no longer accepts account passwords for git push.

Use SSH for this repo:
  ./scripts/setup-github-ssh.sh

Then add the printed public key to GitHub SSH keys and rerun dotup.

EOF
      return 1
      ;;
  esac
}

dotup() {
  local repo msg capture_tokens=0
  repo="$(_dotfiles_repo)" || return
  if [ "${1:-}" = "--tokens" ]; then
    capture_tokens=1
    shift
  fi
  msg="${1:-Update dotfiles from $(hostname -s 2>/dev/null || hostname)}"

  (
    cd "$repo" || exit 1
    _dotfiles_git_preflight || exit 1
    if [ "$capture_tokens" = 1 ]; then
      ./scripts/secrets-capture.sh
    fi
    ./scripts/refresh-from-home.sh
    ./scripts/scan-secrets.sh
    git add -A
    if git diff --cached --quiet; then
      printf 'No dotfiles changes to upload.\n'
      exit 0
    fi
    git commit -m "$msg"
    git push
  )
}

dotdown() {
  local repo
  repo="$(_dotfiles_repo)" || return

  (
    cd "$repo" || exit 1
    git pull --ff-only
    if [ -f secrets/secrets.env.age ]; then
      ./scripts/secrets-install.sh
    fi
    ./scripts/bootstrap.sh
    chezmoi --source "$repo" apply
  )
}
ZSH_HELPERS_EOF
}

sanitize_codex_config() {
  local src="$src_home/.codex/config.toml"
  local dst="$repo_root/dot_codex/private_config.toml.tmpl"
  [[ -f "$src" ]] || return 0
  mkdir -p -- "$(dirname -- "$dst")"
  perl -0pe '
    s#\Q$ENV{HOME}\E#{{ .chezmoi.homeDir }}#g;
    s/headers = \{ Authorization = "Bearer [^"{][^"]*" \}/headers = { Authorization = "Bearer {{ env "SIYUAN_SISYPHUS_TOKEN" }}" }/g;
    s/Authorization = "Bearer [^"{][^"]*"/Authorization = "Bearer {{ env "SIYUAN_SISYPHUS_TOKEN" }}"/g;
    s/GROK_API_KEY = "[^"]*"/GROK_API_KEY = "{{ env "GROK_API_KEY" }}"/g;
    s/TAVILY_API_KEY = "[^"]*"/TAVILY_API_KEY = "{{ env "TAVILY_API_KEY" }}"/g;
  ' "$src" > "$dst"
}

sanitize_claude_providers() {
  local src_dir="$src_home/.claude/providers"
  local dst_dir="$repo_root/dot_claude/providers"
  [[ -d "$src_dir" ]] || return 0
  mkdir -p -- "$dst_dir"

  find "$src_dir" -maxdepth 1 -type f -name '*.json' -print0 |
    while IFS= read -r -d '' src; do
      local base name env_name dst
      base="$(basename -- "$src")"
      name="${base%.json}"
      env_name="$(printf '%s' "$name" | tr '[:lower:]-' '[:upper:]_')"
      dst="$dst_dir/private_${base}.tmpl"
      perl -0pe "s/\"ANTHROPIC_API_KEY\"\\s*:\\s*\"[^\"]*\"/\"ANTHROPIC_API_KEY\": \"{{ env \\\"CLAUDE_PROVIDER_${env_name}_API_KEY\\\" }}\"/g" "$src" > "$dst"
    done
}

write_skill_manifest() {
  local dst="$repo_root/docs/skill-manifest.md"
  mkdir -p -- "$(dirname -- "$dst")"
  {
    printf '# Skill Manifest\n\n'
    printf 'Generated from this machine by `scripts/refresh-from-home.sh`.\n\n'
    printf '## Claude Skills\n\n'
    if [[ -d "$src_home/.claude/skills" ]]; then
      find "$src_home/.claude/skills" -maxdepth 1 -mindepth 1 -type d -print |
        sed "s#^$src_home/.claude/skills/##" | sort | sed 's/^/- /'
    fi
    printf '\n## Codex Skills\n\n'
    if [[ -d "$src_home/.codex/skills" ]]; then
      find "$src_home/.codex/skills" -maxdepth 1 -mindepth 1 -type d -print |
        sed "s#^$src_home/.codex/skills/##" | sort | sed 's/^/- /'
    fi
  } > "$dst"
}

encode_hidden_files() {
  find "$repo_root" \
    -mindepth 2 \
    -type f \
    -name '.*' \
    -not -path "$repo_root/.git/*" \
    -print0 |
    while IFS= read -r -d '' path; do
      local dir base target
      dir="$(dirname -- "$path")"
      base="$(basename -- "$path")"
      target="$dir/dot_${base#.}"
      [[ "$path" == "$target" ]] && continue
      mv -f -- "$path" "$target"
    done
}

encode_literal_skill_scripts() {
  local root

  for root in "$repo_root/dot_claude/skills" "$repo_root/dot_codex/skills"; do
    [[ -d "$root" ]] || continue
    find "$root" -type f \( -name 'run_*' -o -name 'once_*' \) -print0 |
      while IFS= read -r -d '' path; do
        local dir base target
        dir="$(dirname -- "$path")"
        base="$(basename -- "$path")"
        if [[ -x "$path" ]]; then
          target="$dir/executable_literal_$base"
        else
          target="$dir/literal_$base"
        fi
        [[ "$path" == "$target" ]] && continue
        mv -f -- "$path" "$target"
      done
  done
}

need perl
need rsync
need sed
need find

sanitize_zprofile
copy_file "$src_home/.tmux.conf" "$repo_root/dot_tmux.conf"
sanitize_zshrc

copy_tree "$src_home/.config/nvim" "$repo_root/dot_config/nvim" \
  --exclude '.git/' \
  --exclude '.DS_Store'

copy_tree "$src_home/.config/tmux" "$repo_root/dot_config/tmux" \
  --exclude '.git/' \
  --exclude 'plugins/' \
  --exclude '*.bak' \
  --exclude 'cover.png' \
  --exclude '.DS_Store'

copy_file "$src_home/.claude/.gitignore" "$repo_root/dot_claude/dot_gitignore"
copy_file "$src_home/.claude/CLAUDE.md" "$repo_root/dot_claude/CLAUDE.md"
copy_file "$src_home/.claude/README.md" "$repo_root/dot_claude/README.md"
copy_file "$src_home/.claude/settings.json" "$repo_root/dot_claude/settings.json"
copy_file "$src_home/.claude/policy-limits.json" "$repo_root/dot_claude/policy-limits.json"
copy_file "$src_home/.claude/setup.sh" "$repo_root/dot_claude/executable_setup.sh"
copy_file "$src_home/.claude/statusline.sh" "$repo_root/dot_claude/executable_statusline.sh"
copy_file "$src_home/.claude/statusline-claude-hud.sh" "$repo_root/dot_claude/executable_statusline-claude-hud.sh"
copy_file "$src_home/.claude/integration.sh" "$repo_root/dot_claude/integration.sh"
copy_file "$src_home/.claude/integration.fish" "$repo_root/dot_claude/integration.fish"
copy_file "$src_home/.claude/emotion-pack.md" "$repo_root/dot_claude/emotion-pack.md"
copy_file "$src_home/.claude/opus46back.md" "$repo_root/dot_claude/opus46back.md"
copy_file "$src_home/.claude/tutorial.md" "$repo_root/dot_claude/tutorial.md"
copy_file "$src_home/.claude/video-desc.md" "$repo_root/dot_claude/video-desc.md"

copy_tree "$src_home/.claude/agents" "$repo_root/dot_claude/agents" \
  --exclude '.git/' \
  --exclude '.DS_Store'
copy_tree "$src_home/.claude/hooks" "$repo_root/dot_claude/hooks" \
  --exclude '.git/' \
  --exclude '__pycache__/' \
  --exclude '.DS_Store'
remove_tree_symlinks "$repo_root/dot_claude/skills"
copy_tree "$src_home/.claude/skills" "$repo_root/dot_claude/skills" \
  --copy-links \
  --exclude '.git/' \
  --exclude '__pycache__/' \
  --exclude '.venv/' \
  --exclude 'node_modules/' \
  --exclude 'dist/' \
  --exclude '*.tsbuildinfo' \
  --exclude '.DS_Store'
sanitize_claude_providers

copy_file "$src_home/.codex/AGENTS.md" "$repo_root/dot_codex/AGENTS.md"
copy_file "$src_home/.codex/browser/config.toml" "$repo_root/dot_codex/browser/config.toml"
sanitize_codex_config
remove_tree_symlinks "$repo_root/dot_codex/skills"
copy_tree "$src_home/.codex/skills" "$repo_root/dot_codex/skills" \
  --copy-links \
  --exclude '.system/' \
  --exclude '.git/' \
  --exclude '__pycache__/' \
  --exclude '.venv/' \
  --exclude 'node_modules/' \
  --exclude 'dist/' \
  --exclude '*.tsbuildinfo' \
  --exclude '*.zip' \
  --exclude '.DS_Store'

encode_hidden_files
encode_literal_skill_scripts
write_skill_manifest

printf 'Refreshed chezmoi source at %s\n' "$repo_root"
