#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
encrypted="${DOTFILES_SECRETS_FILE:-$repo_root/secrets/secrets.env.age}"
output="${DOTFILES_SECRETS_ENV:-$HOME/.config/dotfiles/secrets.env}"
install_plaintext="${DOTFILES_INSTALL_CAPTURED_SECRETS:-1}"
secret_tmp=""

usage() {
  cat <<'EOF'
Usage: ./scripts/secrets-capture.sh [options]

Scan known local config files for workflow tokens, then encrypt them with a
remembered password into secrets/secrets.env.age. Token values are never printed.

Options:
  --no-install       Do not write the decrypted env to ~/.config/dotfiles/secrets.env.
  -h, --help         Show this help.

Environment:
  DOTFILES_SECRETS_FILE=/path/to/secrets.env.age
  DOTFILES_SECRETS_ENV=~/.config/dotfiles/secrets.env
  DOTFILES_INSTALL_CAPTURED_SECRETS=0|1
EOF
}

parse_args() {
  while (($#)); do
    case "$1" in
      --no-install)
        install_plaintext=0
        ;;
      -h | --help)
        usage
        exit 0
        ;;
      *)
        printf 'Unknown option: %s\n\n' "$1" >&2
        usage >&2
        exit 1
        ;;
    esac
    shift
  done
}

require_age() {
  if ! command -v age >/dev/null 2>&1; then
    printf 'age is not installed. Run ./scripts/install-dev-tools.sh first.\n' >&2
    exit 1
  fi
}

shell_quote() {
  local value
  value="${1:-}"
  printf "'%s'" "${value//\'/\'\\\'\'}"
}

extract_shell_export() {
  local name file
  name="$1"
  file="$2"
  [[ -f "$file" ]] || return 0

  TOKEN_NAME="$name" perl -ne '
    my $name = $ENV{TOKEN_NAME};
    next unless /^\s*(?:export\s+)?\Q$name\E=(.*)\s*$/;
    my $value = $1;
    $value =~ s/\s+#.*$//;
    $value =~ s/^\s+|\s+$//g;
    if ($value =~ /^"((?:\\.|[^"])*)"$/ || $value =~ /^'\''((?:\\.|[^'\''])*)'\''$/) {
      $value = $1;
    }
    $value =~ s/\\"/"/g;
    $value =~ s/\\'\''/'\''/g;
    print $value;
    exit;
  ' "$file"
}

extract_codex_value() {
  local key file
  key="$1"
  file="$2"
  [[ -f "$file" ]] || return 0

  TOKEN_NAME="$key" perl -ne '
    my $key = $ENV{TOKEN_NAME};
    next unless /^\s*\Q$key\E\s*=\s*"([^"]*)"/;
    print $1;
    exit;
  ' "$file"
}

extract_codex_bearer() {
  local file="$HOME/.codex/config.toml"
  [[ -f "$file" ]] || return 0

  perl -ne '
    if (/Authorization\s*=\s*"Bearer\s+([^"]+)"/) {
      print $1;
      exit;
    }
  ' "$file"
}

extract_claude_provider_key() {
  local provider file
  provider="$1"
  file="$HOME/.claude/providers/${provider}.json"
  [[ -f "$file" ]] || return 0

  perl -0ne '
    if (/"ANTHROPIC_API_KEY"\s*:\s*"([^"]*)"/) {
      print $1;
      exit;
    }
  ' "$file"
}

capture_value() {
  local name value
  name="$1"
  value="$2"
  CAPTURED_NAMES+=("$name")
  CAPTURED_VALUES+=("$value")
}

build_env_file() {
  local dst name value i provider provider_upper
  dst="$1"
  CAPTURED_NAMES=()
  CAPTURED_VALUES=()

  capture_value MISTRAL_API_KEY "$(extract_shell_export MISTRAL_API_KEY "$HOME/.zshrc")"
  capture_value FIRECRAWL_API_KEY "$(extract_shell_export FIRECRAWL_API_KEY "$HOME/.zshrc")"
  capture_value JINA_API_KEY "$(extract_shell_export JINA_API_KEY "$HOME/.zshrc")"

  capture_value SIYUAN_SISYPHUS_TOKEN "$(extract_codex_bearer)"
  capture_value GROK_API_KEY "$(extract_codex_value GROK_API_KEY "$HOME/.codex/config.toml")"
  capture_value TAVILY_API_KEY "$(extract_codex_value TAVILY_API_KEY "$HOME/.codex/config.toml")"

  for provider in aigcdesk deepseek evolink glm gpt openrouter qwen; do
    provider_upper="$(printf '%s' "$provider" | tr '[:lower:]-' '[:upper:]_')"
    capture_value "CLAUDE_PROVIDER_${provider_upper}_API_KEY" "$(extract_claude_provider_key "$provider")"
  done

  {
    printf '# Generated by scripts/secrets-capture.sh. Do not commit plaintext.\n\n'
    for i in "${!CAPTURED_NAMES[@]}"; do
      name="${CAPTURED_NAMES[$i]}"
      value="${CAPTURED_VALUES[$i]}"
      printf 'export %s=%s\n' "$name" "$(shell_quote "$value")"
    done
  } > "$dst"
}

report_capture_summary() {
  local i name value found=0 missing=0

  printf 'Captured token variables:\n'
  for i in "${!CAPTURED_NAMES[@]}"; do
    name="${CAPTURED_NAMES[$i]}"
    value="${CAPTURED_VALUES[$i]}"
    if [[ -n "$value" ]]; then
      printf '  ok      %s\n' "$name"
      found=$((found + 1))
    else
      printf '  missing %s\n' "$name"
      missing=$((missing + 1))
    fi
  done
  printf 'Summary: %s found, %s missing.\n' "$found" "$missing"
}

install_plaintext_env() {
  local src="$1"
  [[ "$install_plaintext" == "1" ]] || return 0

  mkdir -p -- "$(dirname -- "$output")"
  umask 077
  cp "$src" "$output"
  chmod 600 "$output"
  printf 'Installed plaintext env to %s\n' "$output"
}

main() {
  local tmp
  parse_args "$@"
  require_age

  mkdir -p -- "$(dirname -- "$encrypted")"
  tmp="$(mktemp)"
  secret_tmp="$tmp"
  trap 'rm -f -- "$secret_tmp" "${encrypted}.tmp"' EXIT
  chmod 600 "$tmp"

  build_env_file "$tmp"
  report_capture_summary

  printf 'Encrypting captured tokens. Enter the password you want to use for this secrets file.\n'
  age --passphrase -o "${encrypted}.tmp" "$tmp"
  mv -f -- "${encrypted}.tmp" "$encrypted"
  printf 'Updated encrypted secrets: %s\n' "$encrypted"

  install_plaintext_env "$tmp"
}

main "$@"
